import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { getImagePath, imagePrefix } from "../utils/getImagePath";

const imageLoader = ({ src, width, height }) => {
    return `${imagePrefix}${src}`;
};

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href={`${imagePrefix}/favicon.ico`} />
            </Head>

            <main className={styles.main}>
                <Image
                    loader={imageLoader}
                    src={getImagePath("/images/random-picture.jpeg")}
                    alt="Random image"
                    width={300}
                    height={300}
                />
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image
                            loader={imageLoader}
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
}
